"""
Service modules for the backend.
"""

from app.services.cache_service import (
    cache_home,
    cache_lyrics,
    cache_search,
    cache_stream_info,
    cache_stream_url,
    delete_cache,
    get_cached_home,
    get_cached_lyrics,
    get_cached_search,
    get_cached_stream_url,
    health_check,
)
from app.services.ytdlp_service import (
    AgeRestrictedError,
    GeoBlockedError,
    RateLimitError,
    StreamInfo,
    VideoNotFoundError,
    YtdlpError,
    cleanup,
    extract_audio_stream,
    extract_stream,
)
from app.services.ytmusic_service import (
    Album,
    AlbumDetails,
    Artist,
    ArtistDetails,
    ContentNotFoundError,
    HomeSection,
    Lyrics,
    Playlist,
    PlaylistDetails,
    SearchResults,
    SearchType,
    Song,
    SongDetails,
    YTMusicAuthError,
    YTMusicError,
    YTMusicRateLimitError,
    YTMusicService,
    get_album_details,
    get_artist_details,
    get_home_feed,
    get_playlist_details,
    get_song_details,
    get_song_lyrics,
    search_music,
    ytmusic_service,
)

__all__ = [
    # ytdlp_service
    "YtdlpError",
    "VideoNotFoundError",
    "GeoBlockedError",
    "RateLimitError",
    "AgeRestrictedError",
    "StreamInfo",
    "extract_stream",
    "extract_audio_stream",
    # cache_service
    "cache_stream_url",
    "cache_stream_info",
    "get_cached_stream_url",
    "cache_search",
    "get_cached_search",
    "cache_home",
    "get_cached_home",
    "cache_lyrics",
    "get_cached_lyrics",
    "delete_cache",
    "health_check",
    # ytmusic_service
    "YTMusicService",
    "YTMusicError",
    "YTMusicAuthError",
    "YTMusicRateLimitError",
    "ContentNotFoundError",
    "SearchType",
    "Song",
    "Artist",
    "Album",
    "Playlist",
    "SongDetails",
    "ArtistDetails",
    "AlbumDetails",
    "PlaylistDetails",
    "Lyrics",
    "HomeSection",
    "SearchResults",
    "ytmusic_service",
    "search_music",
    "get_home_feed",
    "get_song_details",
    "get_artist_details",
    "get_album_details",
    "get_playlist_details",
    "get_song_lyrics",
]
